### ISSUE TITLE
Incorrect function names

### ISSUE THREAD

**Issue by koalefant** [nimgl/nimgl#20]
Some identifiers use incorrect (old?) names and cannot be imported from cimgo.so, in particular I found: 
- igTreeNode (cimgui library contains igTreeNodeStr and igTreeNodePtr instead)
- igTreeNodeEx 
- igPushID

**Comment by lmariscal** [comment]
Hmm, this is a bug that happens at the translation from json to nim. Will have to rewrite some parts of the generator. For the moment I will push 1.71 but will be working also to fix this issue.

**Comment by lmariscal** [comment]
Sorry for the delay, took me longer than I expected. Generator was rewritten with implementations for OpenGL and GLFW updated to it. Changes have been pushed to https://github.com/nimgl/imgui where the independent module resides. Same pushes will be pushed to this repo in the near future.
Data types changed a little mostly ImVector now being a generic type and Enums being Enums instead of just constants. Might need to do some refactor in your project but nothing major.
If you are further interested in why this changes I explained a little further here: https://notes.ldmd.mx/nimgl_1.0.html
