### ISSUE TITLE
Upgrade to cimgui 1.71

### ISSUE THREAD

**Issue by kraptor** [nimgl/nimgl#22]
I've updated all deps for my projects lately and found lots of crashes, due to NimGL expecting cimgui version 1.70 and I was pulling 1.71 in my build scripts.

Would be nice to update NimGL to support 1.71 if possible.

Thanks!

**Comment by lmariscal** [comment]
I have been postponing this upgrade due to an upgrade made into the bindings generator. The new generator changes some syntax mostly on Enums now being Enums instead of Constants and ImVector now being a generic in Nim to comply with the C++ source.
Would like to know if you are okay with refactoring some code, mentioned above Enums and ImVector related. Or you need me to push a fix with the current working solution. If you are okay with the small refactoring I will push a new branch called 1.0 (Because that is the target of the generator rewrite) and will let you know by closing this issue. If you need a solution compatible with the working one I will have to fix the current generator due to some changes in ImGui that broke the generator.
The current generator is already working and you can find it on [nimgl/imgui](https://github.com/nimgl/imgui). If you are interested in the why you can check a small post I made [nimgl_1.0](https://notes.ldmd.mx/nimgl_1.0.html).
Please let me know. And thank you for using NimGL.

**Comment by kraptor** [comment]
Okay! No worries, I can wait :)

I'm 100% in favor of ImVector and proper enums and I will gladly to wait to the next version and refactor once you release a new version.

I went through the post about nimgl 1.0 and all of it really makes sense, so I prefer tot wait and I'll update afterwards, no worries.

BTW, keep it up, you are doing a great work!

**Comment by lmariscal** [comment]
`1.0` branch has been pushed. You can install this specific branch by `nimble install nimgl@#1.0`.
It is using the latest cimgui version together with ImGui 1.71.

Please let me know any issues or desired features or helpers since this branch is still in development. If you wish to only upgrade ImGui bindings to 1.0 you can install or require the [nimgl/imgui](https://github.com/nimgl/imgui) repo directly.
