### ISSUE TITLE
igPushStyleColor receives an ImVec4 instead of a ImU32

### ISSUE THREAD

**Issue by kraptor** [nimgl/nimgl#26]
https://github.com/nimgl/nimgl/blob/991cf5e6c28245ec0144607f500c446aa68f21b3/src/nimgl/imgui.nim#L1608

Proper signature:
```
proc igPushStyleColor*(idx: ImGuiCol, col: ImVec4): void {.imgui_lib, importc: "igPushStyleColor".}
```

**Comment by kraptor** [comment]
Hey Leonardo, if you explain to me how the generator works, I can send patches directly.

**Comment by lmariscal** [comment]
Sure, the generator is located at https://github.com/nimgl/imgui/tree/master/tools. That repo is also an isolated imgui module that can be loaded from nimble.  
To use the generator you must clone the repo recursively since it uses cimgui and cimgui uses imgui. Then run `nimble gen` which will start the generator and output a `imgui.nim` file under the src directory.

The code itself is run by the proc `igGenerate` which calls four procs each in charge of different sections "Enums", "TypeDefs", "Types" and "Procs" each calls the JSON parsers to get the required data. It has different util procs such as "uncapitalize", "isUpper" (Both to help respect PEP1), "translateProc", "translateArray", "translateType" (the three to help translate different signatures from C to Nim).

If you find yourself curious about it feel free to ask me and even open PRs in the imgui repo, but do not worry about asking me to fix library issues. I usually fix them within the smallest time frame possible.

**Comment by lmariscal** [comment]
And it seems you are using the `0.3.6` version of the imgui bindings, `1.0.0` has the correct signatures:
```nim
proc igPushStyleColor*(idx: ImGuiCol, col: uint32): void {.importc: "igPushStyleColorU32".}
proc igPushStyleColor*(idx: ImGuiCol, col: ImVec4): void {.importc: "igPushStyleColor".}
```
https://github.com/nimgl/nimgl/blob/1.0/src/nimgl/imgui.nim#L1555

**Comment by kraptor** [comment]
Yes, I'm still stuck in 0.3.6 as I had no time to upgrade yet. I'll do today, Feel free to close the issue (or tag it with 0.3.6 version).

Would be nice to have a version tag in order to discriminate bugs between versions.
